version: "3.8"
services:
  postgresdb:
    container_name: postgres
    image: postgres:alpine
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
  
  api:
    container_name: api
    restart: always
    build: ./backend
    ports:
      - $SERVER_PORT:$SERVER_PORT
    environment:
      - SERVER_PORT=$SERVER_PORT
      - CLIENT_HOST_URL=$CLIENT_HOST_URL
      - DB_USER=$DB_USER
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
    depends_on:
      - postgresdb

volumes:
  data: {}
